<<<<<<< HEAD:simulator/src-gen/com/yakindu/core/IStatemachine.java
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core;

/**
 * Basic interface for state machines.
 */
public interface IStatemachine {

	/**
	 * Enters the state machine. Sets the state machine into a defined state.
	 */
	public void enter();

	/**
	 * Exits the state machine. Leaves the state machine with a defined state.
	 */
	public void exit();

	/**
	 * Checks whether the state machine is active. 
	 * A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
	 */
	public boolean isActive();

	/**
	 * Checks whether all active states are final. 
	 * If there are no active states then the state machine is considered being incative. In this case this method returns <code>false</code>.
	 */
	public boolean isFinal();
}
=======
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core;

/**
 * Basic interface for state machines.
 */
public interface IStatemachine {

	/**
	 * Enters the state machine. Sets the state machine into a defined state.
	 */
	public void enter();

	/**
	 * Exits the state machine. Leaves the state machine with a defined state.
	 */
	public void exit();

	/**
	 * Checks whether the state machine is active. 
	 * A state machine is active if it has been entered. It is inactive if it has not been entered at all or if it has been exited.
	 */
	public boolean isActive();

	/**
	 * Checks whether all active states are final. 
	 * If there are no active states then the state machine is considered being incative. In this case this method returns <code>false</code>.
	 */
	public boolean isFinal();
}
>>>>>>> 308c2f6b59a427da313ecd842c5fe5e5918e5f8c:simulator/src-gen/com/yakindu/core/IStatemachine.java
