<<<<<<< HEAD
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core.rx;

public interface Observer<T> {

	void next(T value);

}
=======
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core.rx;

public interface Observer<T> {

	void next(T value);

}
>>>>>>> 308c2f6b59a427da313ecd842c5fe5e5918e5f8c
