<<<<<<< HEAD
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core.rx;

import java.util.ArrayList;
import java.util.List;

public class Observable<T> {

	private List<Observer<T>> observers = new ArrayList<>();

	public void next(T value) {
		for (Observer<T> observer : observers) {
			observer.next(value);
		}
	}

	public boolean subscribe(Observer<T> observer) {
		return observer != null ? this.observers.add(observer) : false;
	}

	public boolean unsubscribe(Observer<T> observer) {
		return observer != null ? this.observers.remove(observer) : false;
	}
}
=======
/** Generated by YAKINDU Statechart Tools code generator. */
package com.yakindu.core.rx;

import java.util.ArrayList;
import java.util.List;

public class Observable<T> {

	private List<Observer<T>> observers = new ArrayList<>();

	public void next(T value) {
		for (Observer<T> observer : observers) {
			observer.next(value);
		}
	}

	public boolean subscribe(Observer<T> observer) {
		return observer != null ? this.observers.add(observer) : false;
	}

	public boolean unsubscribe(Observer<T> observer) {
		return observer != null ? this.observers.remove(observer) : false;
	}
}
>>>>>>> 308c2f6b59a427da313ecd842c5fe5e5918e5f8c
