/** Generated by YAKINDU Statechart Tools code generator. */
package de.hpi.mod.sim.trafficlight;

import de.hpi.mod.sim.IStatemachine;
import de.hpi.mod.sim.ITimerCallback;

public interface ITrafficlightStatemachine extends ITimerCallback,IStatemachine {
	public interface SCINorth {
	
		public boolean isRaisedOn();
		
		public boolean isRaisedOff();
		
	}
	
	public SCINorth getSCINorth();
	
	public interface SCIEast {
	
		public boolean isRaisedOn();
		
		public boolean isRaisedOff();
		
	}
	
	public SCIEast getSCIEast();
	
	public interface SCISouth {
	
		public boolean isRaisedOn();
		
		public boolean isRaisedOff();
		
	}
	
	public SCISouth getSCISouth();
	
	public interface SCIWest {
	
		public boolean isRaisedOn();
		
		public boolean isRaisedOff();
		
	}
	
	public SCIWest getSCIWest();
	
}
