/** Generated by YAKINDU Statechart Tools code generator. */
package de.hpi.mod.sim.trafficlight;

import de.hpi.mod.sim.IStatemachine;
import de.hpi.mod.sim.ITimerCallback;

public interface ITrafficlightStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public boolean isRaisedSwitchNorth();
		
		public boolean isRaisedSwitchWest();
		
		public boolean isRaisedSwitchSouth();
		
		public boolean isRaisedSwitchEast();
		
		public void setSCInterfaceOperationCallback(SCInterfaceOperationCallback operationCallback);
	
	}
	
	public interface SCInterfaceOperationCallback {
	
		public boolean robotNorth();
		
		public boolean robotWest();
		
		public boolean robotSouth();
		
		public boolean robotEast();
		
	}
	
	public SCInterface getSCInterface();
	
}
