/** Generated by YAKINDU Statechart Tools code generator. */
package de.hpi.mod.sim.flasher;

import de.hpi.mod.sim.IStatemachine;
import de.hpi.mod.sim.ITimerCallback;

public interface IFlasherStatemachine extends ITimerCallback,IStatemachine {
	public interface SCInterface {
	
		public void raiseStart(long value);
		
		public boolean isRaisedOn();
		
		public boolean isRaisedOff();
		
	}
	
	public SCInterface getSCInterface();
	
}
