/** Generated by YAKINDU Statechart Tools code generator. */
package de.hpi.mod.sim.robot_for_trafficlight;

import de.hpi.mod.sim.IStatemachine;

public interface IRobot_for_trafficlightStatemachine extends IStatemachine {
}
