/** Generated by YAKINDU Statechart Tools code generator. */
package de.hpi.mod.sim.pong;

import de.hpi.mod.sim.IStatemachine;

public interface IPongStatemachine extends IStatemachine {
	public interface SCInterface {
	
	public static final long maxPos = 1;
	
	public static final long minPos = -1;
	
		public void raiseMyPos(long value);
		
		public void raiseBallPos(long value);
		
		public boolean isRaisedUp();
		
		public boolean isRaisedDown();
		
		public long getMaxPos();
		
		public long getMinPos();
		
	}
	
	public SCInterface getSCInterface();
	
}
